# GitHub Actions
name: Create Vue App and Deploy # åç§°
on:
  push:
    branches:
      - master # master åˆ†æ”¯å‘ç”Ÿpushäº‹ä»¶æ—¶è§¦å‘
jobs:
  build-and-deploy: # ä»»åŠ¡
    runs-on: ubuntu-latest # è¿è¡Œç¯å¢ƒ
    steps: # è¿è¡Œæ­¥éª¤
      - name: Checkout
        uses: actions/checkout@master # è·å–æºç 

      - name: Set Node Version
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Create Vue@2 Project
        run: |
          npm install -g @vue/cli
          vue create 200.vue2-ui -d --merge

      - name: Install and Build
        run: |
          cd 200.vue2-ui
          yarn install
          yarn build

      - name: ğŸ“‚ Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          # ftp server
          server: ftpupload.net
          # ftp username
          username: b32_28202196
          # ftp password
          password: ${{ secrets.ftp_password }}
          # local dir
          local-dir: ./200.vue2-ui/dist/
          # Path to upload to on the server. Must end with trailing slash /
          server-dir: /frameworks.22web.org/htdocs/200.vue2-ui/
          # File to Exclude
          exclude: |
            **/.git*
            **/.git*/**
            **/.github*/**
            **/node_modules/**
